-- CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL, firstname TEXT NOT NULL, lastname TEXT NOT NULL);
-- ALTER TABLE users ADD COLUMN letter_count INTEGER DEFAULT 0;

-- CREATE TABLE information (
--     id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
--     user_id INTEGER NOT NULL,
--     intro TEXT,
--     skills TEXT,
--     projects TEXT,
--     FOREIGN KEY (user_id) REFERENCES users (id)
-- );

-- CREATE TABLE letters (
--     id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
--     user_id INTEGER NOT NULL,
--     letter TEXT NOT NULL,
--     date TEXT NOT NULL,
--     company_name TEXT NOT NULL,
--     job_title TEXT NOT NULL,
--     FOREIGN KEY (user_id) REFERENCES users(id)
-- );
